config/routes.rb
Billtastic::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :vendors
  resources :quickbooks do
    collection do
      get :authenticate
      get :oauth_callback
      get :disconnect
    end
  end

  root 'vendors#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:intuit]


  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token.info
    if user = User.where(:email => data["email"]).first
      user
    else
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private

  def set_qb_service(type = 'Vendor')
    oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, session[:token], session[:secret])
    @service = "Quickeebooks::Online::Service::#{type}".constantize.new
    @service.access_token = oauth_client
    @service.realm_id = session[:realm_id]
  end
end

app/controllers/quickbooks_controller.rb
class QuickbooksController < ApplicationController

  def authenticate
    callback = oauth_callback_quickbooks_url
    token = $qb_oauth_consumer.get_request_token(:oauth_callback => callback)
    session[:qb_request_token] = token
    redirect_to("https://appcenter.intuit.com/Connect/Begin?oauth_token=#{token.token}") and return
  end

  def oauth_callback
    at = session[:qb_request_token].get_access_token(:oauth_verifier => params[:oauth_verifier])
    session[:token] = at.token
    session[:secret] = at.secret
    session[:realm_id] = params['realmId']
    flash.notice = "Your QuickBooks account has been successfully linked."
    @msg = 'Redirecting. Please wait.'
    @url = vendors_path
    render 'vendors/close_and_redirect', layout: false
  end

  def disconnect
    set_qb_service('AccessToken')
    result = @service.disconnect
    if result.error_code == '270'
      msg = 'Disconnect failed as OAuth token is invalid. Try connecting again.'
    else
      msg = 'Successfully disconnected from QuickBooks'
    end
    session[:token] = nil
    session[:secret] = nil
    session[:realm_id] = nil
    redirect_to vendors_path, notice: msg
  end



end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_filter :verify_authenticity_token, :only => [:intuit]

  def intuit
    @user = User.find_for_open_id(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Intuit"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.intuit_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  before_action :set_qb_service, only: [:index, :create, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
    if user_signed_in? && session[:token]
      url = @service.url_for_resource(Quickeebooks::Online::Model::Vendor.resource_for_collection)
      @accounts = @service.list
    else
      @accounts = []
    end
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    vendor = Quickeebooks::Online::Model::Vendor.new
    vendor.name = vendor_params[:name]
    vendor.email_address = vendor_params[:email_address]
    @service.create(vendor)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vendor }
      else
        format.html { render action: 'new' }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        vendor = @service.list.entries.find{ |e| e.name == vendor_params[:name] }
        vendor.email_address = vendor_params[:email_address]
        @service.update(vendor)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url }
      format.json { head :no_content }
    end
  end

  def authenticate
    callback = oauth_callback_vendors_url
    token = $qb_oauth_consumer.get_request_token(:oauth_callback => callback)
    session[:qb_request_token] = token
    redirect_to("https://appcenter.intuit.com/Connect/Begin?oauth_token=#{token.token}") and return
  end

  def oauth_callback
    at = session[:qb_request_token].get_access_token(:oauth_verifier => params[:oauth_verifier])
    session[:token] = at.token
    session[:secret] = at.secret
    session[:realm_id] = params['realmId']
    flash.notice = "Your QuickBooks account has been successfully linked."
    @msg = 'Redirecting. Please wait.'
    @url = vendors_path
    render 'close_and_redirect', layout: false
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_vendor
    @vendor = Vendor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vendor_params
    params.require(:vendor).permit(:name, :email_address)
  end

  #def set_qb_service
  #  oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, session[:token], session[:secret])
  #  @vendor_service = Quickeebooks::Online::Service::Vendor.new
  #  @vendor_service.access_token = oauth_client
  #  @vendor_service.realm_id = session[:realm_id]
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quickbooks_helper.rb
module QuickbooksHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Billtastic</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<section id="sign-in">
  <% if user_signed_in? %>
      Signed in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Sign in", new_user_session_path %>
      <ipp:login href="<%= user_omniauth_authorize_path(:intuit) %>"></ipp:login>
  <% end %>
</section>

<% unless session[:token] %>
    <ipp:connectToIntuit></ipp:connectToIntuit>
<% else %>
    <div>
      <%= link_to 'Disconnect from QuickBooks', disconnect_quickbooks_path , data: { confirm: 'Are you sure you want to disconnect?'}  %>
    </div>
<% end %>

<% if notice %>
    <div style="padding: 10px;background: gainsboro;font-weight: 900;width: 50%;"><%= notice %></div>
<% end %>

<%= yield %>

<script type="text/javascript" src="https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js"></script>

<script>
    intuit.ipp.anywhere.setup({menuProxy: '/path/to/blue-dot', grantUrl: '<%= authenticate_quickbooks_url %>'});

    <% if user_signed_in? && !session[:token] %>
    intuit.ipp.anywhere.directConnectToIntuit();
    <% end %>

</script>


</body>
</html>

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

    <div class="field">
      <%= f.label :email_address %><br>
      <%= f.email_field :email_address %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/close_and_redirect.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @msg %></title>
</head>
<body>
<h3><%= @msg %></h3>

<script>
    setTimeout(function(){
        if(window.opener == null){
            window.location = '<%= @url %>';
        }else{
            window.opener.location = '<%= @url %>';
            window.close();
        }
    }, 10000);
</script>
</body>
</html>

app/views/vendors/edit.html.erb
<h1>Editing vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<h1>Remote Vendors</h1>

<table>
  <thead>
  <tr>
    <th>Remote id</th>
    <th>Name</th>
    <th>Email address</th>
  </tr>
  </thead>

  <tbody>
  <% @accounts.entries.each do |vendor| %>
      <tr>
        <td><%= vendor.id %></td>
        <td><%= vendor.name %></td>
        <td><%= vendor.email && vendor.email.address %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<h1>Locals vendors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.name %></td>
        <td><%= vendor.email_address %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @vendor.email_address %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>